### PR TITLE
Button trembling fix

### LINKED ISSUE #88: Sonoff Basic gets reset from iOS
Hi! Thanks for a great project. I've got a question about wifi persistency.

Upd: I've updated the post, please refer to the next comments

Original issue text:
Removed

### PR DESCRIPTION
**Pull request by neptunix**
Resolves #88 

Code provided by @streicherlouw

### CODE REVIEW

File: examples/sonoff_basic/button.c [hunk 1]
```diff
@@ -47,9 +48,17 @@ void button_intr_callback(uint8_t gpio) {
     } else {
         // The button is released. Handle the use cases.
         if ((now - button->last_press_time) * portTICK_PERIOD_MS > button->long_press_time) {
```
Comment (maximkulkin) [inline examples/sonoff_basic/button.c]: This is kind of simplified version of my original button code (which also supported tracking double presses). Given your additions I suggest to simplify it to just calculating event type based on current time value and then merging all the other code into same one branch.

File: examples/sonoff_basic/button.c [hunk 2]
```diff
@@ -38,6 +38,7 @@ void button_intr_callback(uint8_t gpio) {
     uint32_t now = xTaskGetTickCountFromISR();
     if ((now - button->last_event_time)*portTICK_PERIOD_MS < button->debounce_time) {
         // debounce time, ignore events
+        button->last_press_time = 0;
```
Comment (maximkulkin) [inline examples/sonoff_basic/button.c]: Not sure this is needed.
